# Generated by Django 5.1.2 on 2024-10-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='productID',
        ),
    ]
