# Generated by Django 5.1.2 on 2024-10-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='product',
            new_name='product_id',
        ),
    ]
