# Generated by Django 5.1.2 on 2024-10-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0005_supplierperformancereport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='product',
            new_name='productID',
        ),
    ]
